### ISSUE TITLE
Doesn't seem to be able to enable.

### ISSUE THREAD

**Issue by Leos-Khai** [Choominator/Vimp#1]
Is there a special thing you have to to make it read UI? Cause right now the tts only voice out /tts commands, and chat.

**Comment by Choominator** [comment]
@jamestoh-leos - It's supposed to enable automatically, and you should be hearing it speak when you open the game menu or target something, for example.

Some questions:

1. Can you confirm with a sighted person, assuming you have no sight yourself, that the add-on is listed when you click on the Add-Ons button in the character selection screen?
2. If the add-on is seen by the game, can it be enabled manually there?
3. If the add-on is installed and enabled, can you hear anything when you type `/tts sample` on the default chat frame?
4. What operating system are you using?
5. Can you confirm, possibly with the help of a sighted person, or of an app like Seeing AI, that the Lua Warnings popup is not showing?

I believe I've documented the legacy path for World of Warcraft on Windows, which I didn't confirm since I'm on MacOS and have no access to a Windows machine.  From what I read around the current default path is now `C:\User\Public\Games\World of Warcraft\_retail_\Interface\AddOns`.  If the add-on cannot be seen by the game that might be the issue.

I have only tested this add-on with the retail version of the game.  If you try it with the Public Test Realm or classic versions of the game it will likely not work.

If you can't hear anything when you type `/tts sample` then you might need to change the main voice that Blizzard's text-to-speech uses, as I'm relying on that configuration myself.  To change the voice, type `/tts voice N`, where `N` is a number starting from 0.

And finally: I've only tested this add-on with the US English localization of the game.

**Comment by Leos-Khai** [comment]
There seem to not appear in the addon list.
When I do /tts sample, there is no voice.
Using Windows 10.
I do not see a game folder in C:\Users\Public\Games
I am playing retail and Where in the screen is this lua thing suppose to pop up?

**Comment by Choominator** [comment]
OK, there are at least two problems here:

1. Blizzard's main voice for text-to-speech, which is used by Vimp, is either misconfigured or not working on your system, and;
2. The add-on is not installed in the right location, as otherwise it would at least be listed.

To switch the main voice used in text-to-speech, type `/tts voice number`, where the number should be anything starting from 0.  It is possible that the alternative voice, used by Blizzard's text-to-speech to read its own help messages, is working, but the main is not.  Try, for example, switching to voice 0 by typing `/tts voice 0` and then check whether `/tts sample` works.  The add-on will not read anything until the `/tts sample` command can also say something.

To fix the installation problem, and learn the correct path to the game, right-click on the game's icon or press Shift+F10 when the game's shortcut is selected, followed by choosing Open file location from the menu that appears, which should lead you to the location where the game is installed.  From there browse to `_retail_`, `Interface`, `AddOns` and check whether the add-on is installed there inside a directory called Vimp..  GitHub includes the version tag in the directory name like `Vimp-0.1.3` so you might have to change the name to just `Vimp`, though I don't think this is necessary.

**Comment by Leos-Khai** [comment]
Manage to get it to work, It seems changing the main addon directory to just Vimp get it to show up in the addon list.
Thanks for the assist.
